[package]
name = "showroom-embed-test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "showroom-embed-test"
path = "main.rs"

[dependencies]
windows = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
] }
